### ISSUE TITLE
Unknown column error when sending a Private Conversation

### ISSUE THREAD

**Issue by JulianD** [xfrocks/bdApi#112]
After installing the latest version on a XF2.1 forum I get this error when creating a new conversation:

InvalidArgumentException: Unknown column src/XF/Mvc/Entity/Entity.php:206

#0 src/addons/Xfrocks/Api/Repository/Subscription.php(424): XF\Mvc\Entity\Entity->getValue('')
#1 src/addons/Xfrocks/Api/XF/Service/Conversation/Notifier.php(31): Xfrocks\Api\Repository\Subscription->pingConversationMessage('bdapi_reply', Object(XF\Entity\ConversationMessage), Object(Siropu\AdsManager\XF\Entity\User), Object(Siropu\AdsManager\XF\Entity\User))
#2 src/XF/Service/Conversation/Notifier.php(65): Xfrocks\Api\XF\Service\Conversation\Notifier->_sendNotifications('reply', Array, Object(XF\Entity\ConversationMessage))
#3 src/XF/Service/Conversation/Replier.php(179): XF\Service\Conversation\Notifier->notifyReply(Object(XF\Entity\ConversationMessage))
#4 src/XF/Service/Conversation/Replier.php(158): XF\Service\Conversation\Replier->sendNotifications()
#5 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\Conversation\Replier->_save()
#6 src/XF/Pub/Controller/Conversation.php(505): XF\Service\Conversation\Replier->save()
#7 src/XF/Mvc/Dispatcher.php(321): XF\Pub\Controller\Conversation->actionAddReply(Object(XF\Mvc\ParameterBag))
#8 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('XF:Conversation', 'AddReply', Object(XF\Mvc\RouteMatch), Object(XF\Pub\Controller\Conversation), NULL)
#9 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(XF\Pub\Controller\Conversation), NULL)
#10 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#11 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#12 src/XF.php(390): XF\App->run()
#13 index.php(20): XF::runApp('XF\\Pub\\App')
#14 {main}

Everything else worked fine so far.

**Comment by daohoangson** [comment]
Do you have an active subscription for user notification?

**Comment by daohoangson** [comment]
Hello @JulianD

**Comment by daohoangson** [comment]
I'm closing this issue due to inactivity.
