### ISSUE TITLE
Wordpress Fataler Fehler - Ein Fehler vom Typ E_ERROR

### ISSUE THREAD

**Issue by ottosax** [xfrocks/bdApi#163]
Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 78 der Datei /var/www/vhosts/domain.de/wp-content/plugins/xenforo-api-consumer/includes/widget/search.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined function create_function() in /var/www/vhosts/domain.de/wp-content/plugins/xenforo-api-consumer/includes/widget/search.php:78
Stack trace:
#0 /var/www/vhosts/domain.de/wp-content/plugins/xenforo-api-consumer/xenforo-api-consumer.php(98): require_once()
#1 /var/www/vhosts/domain.de/wp-settings.php(418): include_once('...')
#2 /var/www/vhosts/domain.de/wp-config.php(83): require_once('...')
#3 /var/www/vhosts/domain.de/wp-load.php(50): require_once('...')
#4 /var/www/vhosts/domain.de/wp-login.php(12): require('...')
#5 {main}
  thrown

WordPress-Version 5.9.1
Aktives Theme: DarkOrange (Version 7.4)
Aktuelles Plugin: XenForo API Consumer (Version 1.3.5) PHP-Version 8.0.16
Xenforo: 2.2.x
bdAPI: 1.3.5

@xfrocks
I hope you can reproduce this and/or give me a hint to solve this.

**Comment by mjaschen** [comment]
Seems to be fixed in the latest version: https://github.com/xfrocks/bdApi_WordPress/blob/master/xenforo-api-consumer/includes/widget/search.php

Is it possible that you're using a very old version of the `xenforo-api-consumer` code?

(Context: `create_function()` was deprecated with PHP 7.2 and eventually removed with PHP 8.0.)

**Comment by ottosax** [comment]
Seems to be gone after update to API 1.3.6 - right.

I doesnt see the latest version just bevore... damn. ;-)

**Comment by daohoangson** [comment]
That's great to hear. Thanks @mjaschen for the assist.
