### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thuongtin** [xfrocks/bdApi#18]
Fatal error: Uncaught TypeError: Argument 1 passed to XenForo_Application::handleException() must be an instance of Exception, instance of Error given in /home/cuongphonghoi.com/public_html/library/XenForo/Application.php:375 Stack trace: #0 [internal function]: XenForo_Application::handleException(Object(Error)) #1 {main} thrown in /home/cuongphonghoi.com/public_html/library/XenForo/Application.php on line 375

**Comment by daohoangson** [comment]
Do you have steps to reproduce this issue? Also, which version are you on?

**Comment by Azzazelllo** [comment]
Информация об ошибке
ErrorException: Fatal Error: XenForo_Autoloader::main(): Failed opening required '/home/sitename/web/sitename/public_html/library/bdApi/Lib/oauth2-server-php/src/OAuth2/Autoloader.php' (include_path='/home/sitename/web/sitename/public_html/library:.:.:/usr/share/php') - library/bdApi/OAuth2.php:3
Сгенерирована пользователем: Неизвестная учётная запись, 3 мин. назад

Трассировка стэка
#0 [internal function]: XenForo_Application::handleFatalError() 
#1 {main}

Содержимое запроса:
array(3) {
  ["url"] => string(24) "https://sitename/api/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by daohoangson** [comment]
Looks like you check out the git repo without running `git submodule update
--init`

**Comment by Azzazelllo** [comment]
How to fix it ? After installing the add-on, I did not make any changes. I would be very grateful if you could tell me how to fix it :)

**Comment by daohoangson** [comment]
Where did you download it?

**Comment by Azzazelllo** [comment]
https://github.com/xfrocks/bdApi

**Comment by daohoangson** [comment]
If you download directly from github, you need to run `git submodule update
--init` to download dependencies.

**Comment by Azzazelllo** [comment]
How to do it ? Pardon I the first time with so face :(

**Comment by ghost** [comment]
If you are not familiar with git, please download the add-on package from
xenforo.com. This repository is for development only.

**Comment by Azzazelllo** [comment]
Thanks figured it out ;) 
But there was a new error:
"SITE.NAME returned an unknown error. Please try again later."

**Comment by Azzazelllo** [comment]
Информация об ошибке: 
XenForo_Exception: Key "access_token" not found in POST `oauth/token/`: {"error":"invalid_grant","error_description":"Authorization code doesn't exist or is invalid for the client"} - library/bdApiConsumer/Helper/Api.php:247
Сгенерирована пользователем: Неизвестная учётная запись, минуту назад

Трассировка стэка: 
#0 /home/site/web/site/public_html/library/bdApiConsumer/Helper/Api.php(198): bdApiConsumer_Helper_Api::_request('POST', Array, 'oauth/token/', '', 'access_token', Array)
#1 /home/site/web/site/public_html/library/bdApiConsumer/Helper/Api.php(68): bdApiConsumer_Helper_Api::_post(Array, 'oauth/token/', '', 'access_token', Array)
#2 /home/site/web/site/public_html/library/bdApiConsumer/XenForo/ControllerPublic/Register.php(44): bdApiConsumer_Helper_Api::getAccessTokenFromCode(Array, 'ad4f5825de5fd0a...', 'https://site/...')
#3 /home/site/web/site/public_html/library/XenForo/FrontController.php(369): bdApiConsumer_XenForo_ControllerPublic_Register->actionExternal()
#4 /home/site/web/site/public_html/library/XenForo/FrontController.php(152): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#5 /home/site/web/site/public_html/index.php(13): XenForo_FrontController->run()
#6 {main}

Содержимое запроса: 
array(3) {
  ["url"] => string(100) "https://site/register/external?provider=98373&code=ad4f5825de5fd0a5e60e0ce8f8df6a3380493c21&state="
  ["_GET"] => array(4) {
    ["/register/external"] => string(0) ""
    ["provider"] => string(5) "98373"
    ["code"] => string(40) "ad4f5825de5fd0a5e60e0ce8f8df6a3380493c21"
    ["state"] => string(0) ""
  }
  ["_POST"] => array(0) {
  }
}

? :(

**Comment by daohoangson** [comment]
Looks like mismatched clock time between servers. Are you running each site on its own server? Can you check their clock?

**Comment by daohoangson** [comment]
Closing due to inactivity.
