### ISSUE TITLE
Call to a member function getUserProviderConfig() on null

### ISSUE THREAD

**Issue by luutruong** [xfrocks/bdApi#96]
```
Error: Call to a member function getUserProviderConfig() on null src/XF/Service/User/Tfa.php:124
Generated by: Unknown account Nov 26, 2018 at 11:33 PM
Stack trace
#0 src/addons/Xfrocks/Api/Controller/OAuth2.php(244): XF\Service\User\Tfa->verify(Object(XF\Http\Request), 'totp, backup')
#1 src/addons/Xfrocks/Api/Controller/OAuth2.php(195): Xfrocks\Api\Controller\OAuth2->runTfaValidation(Object(Xfrocks\Api\XF\ApiOnly\Entity\User))
#2 src/addons/Xfrocks/Api/OAuth2/Server.php(427): Xfrocks\Api\Controller\OAuth2->verifyCredentials('****', '****')
#3 [internal function]: Xfrocks\Api\OAuth2\Server->Xfrocks\Api\OAuth2\{closure}('***', '****')
#4 src/addons/Xfrocks/Api/vendor/league/oauth2-server/src/Grant/PasswordGrant.php(128): call_user_func(Object(Closure), '****', '......')
#5 src/addons/Xfrocks/Api/vendor/league/oauth2-server/src/AuthorizationServer.php(275): League\OAuth2\Server\Grant\PasswordGrant->completeFlow()
#6 src/addons/Xfrocks/Api/OAuth2/Server.php(433): League\OAuth2\Server\AuthorizationServer->issueAccessToken()
#7 src/addons/Xfrocks/Api/Controller/OAuth2.php(29): Xfrocks\Api\OAuth2\Server->grantFinalize(Object(Xfrocks\Api\Controller\OAuth2))
#8 src/XF/Mvc/Dispatcher.php(249): Xfrocks\Api\Controller\OAuth2->actionPostToken(Object(XF\Mvc\ParameterBag))
#9 src/addons/Xfrocks/Api/XF/ApiOnly/Mvc/Dispatcher.php(40): XF\Mvc\Dispatcher->dispatchClass('Xfrocks:OAuth2', 'PostToken', 'json', Object(XF\Mvc\ParameterBag), '', Object(Xfrocks\Api\Controller\OAuth2), NULL)
#10 src/XF/Mvc/Dispatcher.php(88): Xfrocks\Api\XF\ApiOnly\Mvc\Dispatcher->dispatchClass('Xfrocks:OAuth2', 'post/token', 'json', Object(XF\Mvc\ParameterBag), '', Object(Xfrocks\Api\Controller\OAuth2), NULL)
#11 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#12 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#13 src/XF.php(329): XF\App->run()
#14 api/index.php(4): XF::runApp('Xfrocks\\Api\\App')
#15 {main}
```

**Comment by daohoangson** [comment]
Chắc cái này check `isset($providers[$tfaProvider])` là được nhỉ?
